Add video converter files
jpsandovaln/AT14-SERVICES pull request #4
Opened 2021-07-20 01:08 UTC by edwinPato

I added the classes for processes the video converter with ffmpeg. I am adding the ffmpeg.exe too. I need your opinion about my job. Thanks! :)

2021-07-20 18:24 UTC, serqiiiio approved these changes

2021-07-20 18:24 UTC, serqiiiio commented
Nice Job !

2021-07-21 04:46 UTC, stellith requested changes
It works!, only missing to add a newline at end of "compiler" and "buildCmdVInvertVideo" files.

2021-07-21 05:16 UTC, edwinPato commented
> It works!, only missing to add a newline at end of "compiler" and "buildCmdVInvertVideo" files.

I implemented the agreed code conventions in our group meeting and the line break at the end of each .js file.

2021-07-21 17:54 UTC, stellith approved these changes

2021-07-21 17:57 UTC, merged